name = "pichub"
main = "worker/index.js"
# pages_build_output_dir = "src"
compatibility_date = "2025-03-30"
compatibility_flags = ["nodejs_compat"]

# 绑定R2存储桶
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pichub"

# D1数据库配置
[[d1_databases]]
binding = "DB" 
database_name = "pichub"
database_id = "07e0134c-593e-4c65-8cc6-62f7f295754b"

# 环境变量配置
[vars]
MAX_FILE_SIZE = "52428800" # 50MB in bytes
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp,image/gif,image/svg+xml"
CORS_ALLOW_ORIGIN = "*" # 使用"*"允许所有来源，或设置特定域名
CACHE_CONTROL = "public, max-age=31536000" # 1年缓存
ALLOWED_REFERERS = "*"  # 防盗链配置，域名列表用逗号分隔，例如: "example.com,test.org" 或 "*" 允许所有
DEFAULT_IMAGE = ""      # 可选: 防盗链时显示的默认图片文件名
CF_TOKEN = ""
CF_EMAIL = ""
CF_ACCOUNT_ID = ""

# 需要在Cloudflare的Worker界面中设置以下秘密环境变量:
# - UPLOAD_API_TOKEN: 用于验证上传请求的API令牌
# - JWT_SECRET: 用于JWT签名的密钥 
